version: '3'

networks: 
  web:

volumes:
  server:

services:

  client:
    restart: on-failure
    build: 
      args:
        - REACT_APP_API_SOCKET_PATH=/api/socket.io
        - REACT_APP_API_ADDRESS=/
      context: ./client
      dockerfile: Dockerfile
    container_name: client
    ports:
      - 80:80
      - 443:443
    networks: 
      - web
    depends_on: 
      - server
    volumes:
      - /etc/letsencrypt/:/usr/local/nginx/conf/ssl:ro
  
  server:
    restart: on-failure
    build: 
      context: ./server
      dockerfile: Dockerfile
    container_name: server
    environment:
      SOCKET_IO_PATH: /api/socket.io
      DATABASE_FILE: /var/lib/data/database.db
      SESSION_STORE_PATH: /var/lib/data/sessions
      CLIENT_HTML_INDEX_URL: http://client:8080/
    networks: 
      - web
    volumes:
      - server:/var/lib/data/:rw
                